#!/bin/bash

echo "=== Testing Mnemosyne Task System Frontend ==="
echo ""
echo "✅ Backend is running on http://localhost:8000"
echo "✅ Frontend is running on http://localhost:3000"
echo ""
echo "To test the task system:"
echo ""
echo "1. Open http://localhost:3000 in your browser"
echo "2. Login with your test user credentials"
echo "3. Click on 'Tasks' card on the dashboard"
echo "4. Create a new task with:"
echo "   - Title: 'Test Quest'"
echo "   - Quest Type: Solo"
echo "   - Difficulty: 3"
echo "5. Click 'Start' on the task"
echo "6. Click 'Complete' to earn XP"
echo ""
echo "Expected results:"
echo "- Task creation should work"
echo "- Starting task should change status to 'in_progress'"
echo "- Completing task should show XP gained (e.g., '+30 XP')"
echo "- Total XP should update at the top"
echo ""
echo "Current backend logs show tasks are working:"
docker compose logs backend --tail 5 | grep tasks