"""Update receipt type enum

Revision ID: 063bbc5e8259
Revises: 4ccf320d9727
Create Date: 2025-08-27 03:06:57.225249+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063bbc5e8259'
down_revision: Union[str, None] = '4ccf320d9727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_quest_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_visibility_mask'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_visibility_mask'), 'tasks', ['visibility_mask'], unique=False)
    op.create_index(op.f('ix_tasks_status_user_id'), 'tasks', ['status', 'user_id'], unique=False)
    op.create_index(op.f('ix_tasks_quest_type'), 'tasks', ['quest_type'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    # ### end Alembic commands ###
