"""add_negotiation_tables_complete

Revision ID: e5641d2d08e0
Revises: 45f36fd8abd5
Create Date: 2025-10-14 01:45:01.617288+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5641d2d08e0'
down_revision: Union[str, None] = '45f36fd8abd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('initiator_id', sa.UUID(), nullable=False),
    sa.Column('participant_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('joined_participant_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('required_consensus_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'NEGOTIATING', 'CONSENSUS_REACHED', 'BINDING', 'TERMINATED', 'EXPIRED', 'DISPUTED', name='negotiationstatus'), nullable=False),
    sa.Column('current_terms', sa.JSON(), nullable=True),
    sa.Column('terms_version', sa.Integer(), nullable=True),
    sa.Column('terms_history', sa.JSON(), nullable=True),
    sa.Column('acceptances', sa.JSON(), nullable=True),
    sa.Column('finalizations', sa.JSON(), nullable=True),
    sa.Column('negotiation_deadline', sa.DateTime(), nullable=True),
    sa.Column('finalization_deadline', sa.DateTime(), nullable=True),
    sa.Column('binding_hash', sa.String(length=64), nullable=True),
    sa.Column('binding_timestamp', sa.DateTime(), nullable=True),
    sa.Column('binding_terms', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('negotiation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('consensus_reached_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negotiation_escrows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('negotiation_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_identifier', sa.String(length=200), nullable=False),
    sa.Column('locked_amount', sa.Float(), nullable=True),
    sa.Column('is_locked', sa.String(length=20), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('release_condition', sa.String(length=20), nullable=True),
    sa.Column('lock_hash', sa.String(length=64), nullable=True),
    sa.Column('lock_signature', sa.String(length=512), nullable=True),
    sa.Column('release_signature', sa.String(length=512), nullable=True),
    sa.Column('escrow_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negotiation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('negotiation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.Enum('INITIATE', 'JOIN', 'OFFER', 'COUNTER_OFFER', 'ACCEPT', 'REJECT', 'WITHDRAW', 'FINALIZE', 'DISPUTE', name='negotiationmessagetype'), nullable=False),
    sa.Column('terms', sa.JSON(), nullable=True),
    sa.Column('terms_version', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('in_response_to_message_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['in_response_to_message_id'], ['negotiation_messages.id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('negotiation_messages')
    op.drop_table('negotiation_escrows')
    op.drop_table('negotiations')
    # ### end Alembic commands ###
