"""Add cryptographic hash fields to trust events

Revision ID: 45f36fd8abd5
Revises: 1c9ed6be39ea
Create Date: 2025-10-14 01:13:15.565347+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f36fd8abd5'
down_revision: Union[str, None] = '1c9ed6be39ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
