"""Add receipts table for transparency and audit trail

Revision ID: 4ccf320d9727
Revises: add_game_mechanics
Create Date: 2025-08-25 06:12:41.576813+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ccf320d9727'
down_revision: Union[str, None] = 'add_game_mechanics'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('receipt_type', sa.Enum('MEMORY_CREATE', 'MEMORY_UPDATE', 'MEMORY_DELETE', 'MEMORY_SEARCH', 'TASK_CREATE', 'TASK_UPDATE', 'TASK_COMPLETE', 'TASK_DELETE', 'CHAT_MESSAGE', 'PERSONA_MODE_CHANGE', 'WORLDVIEW_UPDATE', 'AUTH_LOGIN', 'AUTH_LOGOUT', 'TRUST_EXCHANGE', 'CONSENT_GIVEN', 'CONSENT_REVOKED', 'AGENT_ACTION', name='receipttype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('persona_mode', sa.String(length=50), nullable=True),
    sa.Column('worldview_profile', sa.JSON(), nullable=True),
    sa.Column('decisions_made', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('alternatives_considered', sa.JSON(), nullable=True),
    sa.Column('consent_basis', sa.String(length=255), nullable=True),
    sa.Column('data_categories', sa.JSON(), nullable=True),
    sa.Column('privacy_impact', sa.String(length=50), nullable=True),
    sa.Column('user_visible', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('service_version', sa.String(length=50), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('parent_receipt_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    # ### end Alembic commands ###
