"""Add cryptographic hash fields to receipts

Revision ID: 1c9ed6be39ea
Revises: 063bbc5e8259
Create Date: 2025-10-14 01:07:20.611574+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9ed6be39ea'
down_revision: Union[str, None] = '063bbc5e8259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('receipts', sa.Column('previous_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'previous_hash')
    op.drop_column('receipts', 'content_hash')
    # ### end Alembic commands ###
