version: '3.8'

services:
  shadow-ai:
    build: .
    ports:
      - "8001:8000"
    environment:
      - LLM_BASE_URL=${LLM_BASE_URL}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE}
      - EMBEDDING_BASE_URL=${EMBEDDING_BASE_URL}
      - EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
    env_file:
      - .env
    restart: unless-stopped
